<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'EChamado.Client'">
    <!-- Evita baixar analyzers implícitos quando estamos offline -->
    <DisableImplicitComponentsAnalyzers>true</DisableImplicitComponentsAnalyzers>
    <DisableImplicitAspNetCoreAnalyzers>true</DisableImplicitAspNetCoreAnalyzers>
  </PropertyGroup>
</Project>
